# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'narsha_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 712)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AnalysisButton = QtWidgets.QPushButton(self.centralwidget)
        self.AnalysisButton.setGeometry(QtCore.QRect(100, 480, 210, 40))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.AnalysisButton.setFont(font)
        self.AnalysisButton.setStyleSheet("background-color: rgb(58, 116, 154);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #ffffff\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("48390746_202618100682575_8438452542874058752_n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AnalysisButton.setIcon(icon)
        self.AnalysisButton.setIconSize(QtCore.QSize(20, 20))
        self.AnalysisButton.setShortcut("")
        self.AnalysisButton.setObjectName("AnalysisButton")
        self.FolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.FolderButton.setGeometry(QtCore.QRect(100, 550, 210, 40))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.FolderButton.setFont(font)
        self.FolderButton.setStyleSheet("background-color: rgb(58, 116, 154);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #ffffff\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("48416912_1982736148469483_4136976498814877696_n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FolderButton.setIcon(icon1)
        self.FolderButton.setIconSize(QtCore.QSize(20, 20))
        self.FolderButton.setShortcut("")
        self.FolderButton.setObjectName("FolderButton")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(100, 620, 210, 40))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.SaveButton.setFont(font)
        self.SaveButton.setStyleSheet("background-color: rgb(58, 116, 154);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid #ffffff\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("48403613_290865764898025_369573556339605504_n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveButton.setIcon(icon2)
        self.SaveButton.setIconSize(QtCore.QSize(20, 20))
        self.SaveButton.setShortcut("")
        self.SaveButton.setObjectName("SaveButton")
        self.dicom_frame = QtWidgets.QFrame(self.centralwidget)
        self.dicom_frame.setGeometry(QtCore.QRect(410, 10, 671, 431))
        self.dicom_frame.setStyleSheet("background-color: rgb(72, 103, 154);")
        self.dicom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dicom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dicom_frame.setObjectName("dicom_frame")
        self.asset_label = QtWidgets.QLabel(self.dicom_frame)
        self.asset_label.setGeometry(QtCore.QRect(10, 10, 651, 381))
        self.asset_label.setText("")
        self.asset_label.setObjectName("asset_label")
        self.innerText_label = QtWidgets.QLabel(self.dicom_frame)
        self.innerText_label.setGeometry(QtCore.QRect(10, 400, 651, 20))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(12)
        self.innerText_label.setFont(font)
        self.innerText_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.innerText_label.setAlignment(QtCore.Qt.AlignCenter)
        self.innerText_label.setObjectName("innerText_label")
        self.chart_label = QtWidgets.QLabel(self.dicom_frame)
        self.chart_label.setGeometry(QtCore.QRect(420, 10, 241, 411))
        self.chart_label.setObjectName("chart_label")
        
        self.list_label = QtWidgets.QLabel(self.centralwidget)
        self.list_label.setGeometry(QtCore.QRect(410, 510, 411, 151))
        self.list_label.setStyleSheet("border:2px solid rgb(72, 103, 154);")
        self.list_label.setText("")
        self.list_label.setTextFormat(QtCore.Qt.PlainText)
        self.list_label.setObjectName("list_label")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(50, 20, 311, 371))
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(830, 510, 251, 151))
        self.result_label.setStyleSheet("border:2px solid rgb(72, 103, 154);")
        self.result_label.setText("")
        self.result_label.setTextFormat(QtCore.Qt.PlainText)
        self.result_label.setObjectName("result_label")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(45, 410, 321, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(16)
        self.title_label.setFont(font)
        self.title_label.setTextFormat(QtCore.Qt.PlainText)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.result_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.result_label_1.setGeometry(QtCore.QRect(850, 540, 56, 12))
        self.result_label_1.setObjectName("result_label_1")
        self.result_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.result_label_2.setGeometry(QtCore.QRect(920, 620, 56, 20))
        self.result_label_2.setObjectName("result_label_2")
        self.list_label_name_1 = QtWidgets.QLabel(self.centralwidget)
        self.list_label_name_1.setGeometry(QtCore.QRect(410, 490, 56, 12))
        self.list_label_name_1.setObjectName("list_label_name_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AnalysisButton.setText(_translate("MainWindow", "Analysis"))
        self.FolderButton.setText(_translate("MainWindow", "Folder"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.innerText_label.setText(_translate("MainWindow", "Click Folder Button and Analysis"))
        self.chart_label.setText(_translate("MainWindow", "TextLabel"))
        self.title_label.setText(_translate("MainWindow", "X-ray Decomposition Analyzer"))
        self.result_label_1.setText(_translate("MainWindow", "TextLabel"))
        self.result_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.list_label_name_1.setText(_translate("MainWindow", "TextLabel"))

